version: "3.9" 

services:
  flask-app:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "5000:5000" 
    environment:
      FLASK_APP: app.py
      FLASK_ENV: production
      APP_HOST: 0.0.0.0
      APP_PORT: 5000
    volumes:
      - ./jsons:/app/jsons 
      - ./oficial_pasta_envio:/app/oficial_pasta_envio

volumes:
  jsons: {}
  oficial_pasta_envio: {}
